// First define your cloud data, using `text` and `size` properties:

    var skillsToDraw = [
    	{ text: 'Bontrager, Philip' , size: 6},
{ text: 'Khalifa, Ahmed' , size: 39},
{ text: 'Anderson, Damien' , size: 9},
{ text: 'Stephenson, Matthew' , size: 15},
{ text: 'Salge, Christoph' , size: 12},
{ text: 'Togelius, Julian' , size: 99},
{ text: 'Gaina, Raluca D' , size: 27},
{ text: 'Sequeira, Pedro' , size: 3},
{ text: 'Melo, Francisco S' , size: 3},
{ text: 'Paiva, Ana' , size: 3},
{ text: 'Levine, John' , size: 9},
{ text: 'Renz, Jochen' , size: 9},
{ text: 'Nantes, Alfredo' , size: 3},
{ text: 'Brown, Ross' , size: 3},
{ text: 'Maire, Frederic' , size: 3},
{ text: 'Jia, Baozhu' , size: 3},
{ text: 'Ebner, Marc' , size: 3},
{ text: 'Schack, Christian' , size: 3},
{ text: 'Zhou, Hongwei' , size: 3},
{ text: 'Gong, Yichen' , size: 3},
{ text: 'Mugrai, Luvneesh' , size: 3},
{ text: 'Nealen, Andy' , size: 39},
{ text: 'Laviers, Kennard' , size: 3},
{ text: 'Sukthankar, Gita' , size: 3},
{ text: 'Horn, Britton' , size: 6},
{ text: 'Miller, Josh' , size: 3},
{ text: 'Smith, Gillian' , size: 12},
{ text: 'Cooper, Seth' , size: 3},
{ text: 'Hagelback, Johan' , size: 3},
{ text: 'Johansson, Stefan' , size: 3},
{ text: 'Eger, Markus' , size: 3},
{ text: 'Martens, Chris' , size: 3},
{ text: 'Packard, Brandon' , size: 6},
{ text: 'Ontan{\'o}n, Santiago' , size: 9},
{ text: 'Moraes, Rubens' , size: 6},
{ text: 'Marino, Julian' , size: 3},
{ text: 'Lelis, Levi' , size: 6},
{ text: 'Nascimento, Mario' , size: 3},
{ text: 'Kartal, Bilal' , size: 3},
{ text: 'Hernandez-Leal, Pablo' , size: 3},
{ text: 'Taylor, Matthew E' , size: 3},
{ text: 'Oh, Junhyuk' , size: 3},
{ text: 'Guo, Xiaoxiao' , size: 6},
{ text: 'Lee, Honglak' , size: 6},
{ text: 'Lewis, Richard L' , size: 6},
{ text: 'Singh, Satinder' , size: 9},
{ text: 'Buro, Michael' , size: 12},
{ text: 'Cutumisu, Maria' , size: 3},
{ text: 'Szafron, Duane' , size: 6},
{ text: 'Bowling, Michael H' , size: 3},
{ text: 'Sutton, Richard S' , size: 6},
{ text: 'Small, Ryan K' , size: 3},
{ text: 'Barata, Alexandre' , size: 3},
{ text: 'Santos, Pedro' , size: 3},
{ text: 'Prada, Rui' , size: 3},
{ text: 'Hoover, Amy K' , size: 9},
{ text: 'Folajimi, Yetunde' , size: 3},
{ text: 'Barnes, Jackie' , size: 3},
{ text: 'Harteveld, Casper' , size: 6},
{ text: 'Machado, Tiago' , size: 12},
{ text: 'Gopstein, Daniel' , size: 3},
{ text: 'Nov, Oded' , size: 3},
{ text: 'de Mesentier Silva, Fernando' , size: 18},
{ text: 'Lee, Scott' , size: 15},
{ text: 'Jain, Satvik' , size: 3},
{ text: 'Verma, Siddharth' , size: 3},
{ text: 'Kumar, Swaraj' , size: 3},
{ text: 'Aggarwal, Swati' , size: 3},
{ text: 'McCoy, Joshua' , size: 3},
{ text: 'Mateas, Michael' , size: 12},
{ text: 'Mohan, Shiwali' , size: 3},
{ text: 'Laird, John' , size: 3},
{ text: 'Sironi, Chiara F' , size: 15},
{ text: 'Winands, Mark HM' , size: 24},
{ text: 'Perez-Liebana, Diego' , size: 48},
{ text: 'Drageset, Olve' , size: 3},
{ text: 'Ilhan, Erc{\""u}ment' , size: 6},
{ text: 'Balla, Martin' , size: 6},
{ text: 'Lucas, Simon M' , size: 48},
{ text: 'P{\'e}rez-Li{\'e}bana, Diego' , size: 6},
{ text: 'Samothrakis, Spyridon' , size: 9},
{ text: 'Schaul, Tom' , size: 3},
{ text: 'Weber, Ben' , size: 3},
{ text: 'Jhala, Arnav' , size: 6},
{ text: 'Sifa, Rafet' , size: 3},
{ text: 'Bauckhage, Christian' , size: 3},
{ text: 'Stahlke, Samantha' , size: 3},
{ text: 'Nova, Atiya' , size: 3},
{ text: 'Mirza-Babaei, Pejman' , size: 3},
{ text: 'Green, Michael Cerny' , size: 15},
{ text: 'Barros, Gabriella AB' , size: 12},
{ text: 'Bergdahl, Joakim' , size: 3},
{ text: 'Gordillo, Camilo' , size: 3},
{ text: 'Tollmar, Konrad' , size: 3},
{ text: 'Gissl{\'e}n, Linus' , size: 3},
{ text: 'Robertson, Justus' , size: 3},
{ text: 'Young, R Michael' , size: 3},
{ text: 'Liu, Simon' , size: 6},
{ text: 'Chaoran, Li' , size: 6},
{ text: 'Yue, Li' , size: 6},
{ text: 'Heng, Ma' , size: 6},
{ text: 'Xiao, Hou' , size: 6},
{ text: 'Yiming, Shen' , size: 6},
{ text: 'Licong, Wang' , size: 6},
{ text: 'Ze, Chen' , size: 6},
{ text: 'Xianghao, Guo' , size: 6},
{ text: 'Hengtong, Lu' , size: 6},
{ text: 'others' , size: 12},
{ text: 'Glenn, James' , size: 3},
{ text: 'Brunstad, Rob' , size: 3},
{ text: 'Charity, Megan' , size: 3},
{ text: 'Grau-Moya, Jordi' , size: 3},
{ text: 'Leibfried, Felix' , size: 3},
{ text: 'Bou-Ammar, Haitham' , size: 3},
{ text: 'Wang, Baoxiang' , size: 3},
{ text: 'Sun, Tongfang' , size: 3},
{ text: 'Zheng, Xianjun Sam' , size: 3},
{ text: 'Justesen, Niels' , size: 6},
{ text: 'Uth, Lasse M{\o}ller' , size: 3},
{ text: 'Jakobsen, Christopher' , size: 3},
{ text: 'Moore, Peter David' , size: 3},
{ text: 'Risi, Sebastian' , size: 15},
{ text: 'Pfau, Johannes' , size: 9},
{ text: 'Smeddinck, Jan David' , size: 6},
{ text: 'Bikas, Ioannis' , size: 3},
{ text: 'Malaka, Rainer' , size: 9},
{ text: 'Lipovetzky, Nir' , size: 3},
{ text: 'Ramirez, Miquel' , size: 3},
{ text: 'Geffner, Hector' , size: 6},
{ text: 'Dharna, Aaron' , size: 3},
{ text: 'Soros, LB' , size: 3},
{ text: 'Sfikas, Konstantinos' , size: 3},
{ text: 'Liapis, Antonios' , size: 9},
{ text: 'Devlin, Sam' , size: 9},
{ text: 'Anspoka, Anastasija' , size: 3},
{ text: 'Sephton, Nick' , size: 3},
{ text: 'Cowling, Peter' , size: 6},
{ text: 'Rollason, Jeff' , size: 6},
{ text: 'Chu, Chun Yin' , size: 3},
{ text: 'Hashizume, Hisaaki' , size: 3},
{ text: 'Guo, Zikun' , size: 3},
{ text: 'Harada, Tomohiro' , size: 3},
{ text: 'Thawonmas, Ruck' , size: 9},
{ text: 'Huang, Shiyu' , size: 3},
{ text: 'Su, Hang' , size: 6},
{ text: 'Zhu, Jun' , size: 6},
{ text: 'Chen, Ting' , size: 3},
{ text: 'Gillespie, Lauren E' , size: 3},
{ text: 'Gonzalez, Gabriela R' , size: 3},
{ text: 'Schrum, Jacob' , size: 3},
{ text: 'Muise, Christian' , size: 3},
{ text: 'Belle, Vaishak' , size: 3},
{ text: 'McIlraith, Sheila' , size: 3},
{ text: 'Rubin, Jonathan' , size: 3},
{ text: 'Watson, Ian' , size: 3},
{ text: 'Holmg{\aa}rd, Christoffer' , size: 3},
{ text: 'Yannakakis, Georgios' , size: 3},
{ text: 'Wang, Xiaoshi' , size: 3},
{ text: 'Xiaoxiao Guo' , size: 3},
{ text: 'Satinder Singh' , size: 3},
{ text: 'R. L. Lewis' , size: 3},
{ text: 'H. Lee' , size: 3},
{ text: 'Drake, John' , size: 3},
{ text: 'Safonova, Alla' , size: 3},
{ text: 'Likhachev, Maxim' , size: 3},
{ text: 'Noam Brown' , size: 3},
{ text: 'T. Sandholm' , size: 3},
{ text: 'Brandon Amos' , size: 3},
{ text: 'Yaguchi, Takanobu' , size: 3},
{ text: 'Iima, Hitoshi' , size: 3},
{ text: 'Bernardini, Sara' , size: 3},
{ text: 'Porayska-Pomsta, Kaska' , size: 3},
{ text: 'Sampath, Harini' , size: 3},
{ text: 'Boron, Jonathan' , size: 3},
{ text: 'Darken, Chris' , size: 3},
{ text: 'Khan, Gul Muhammad' , size: 3},
{ text: 'Miller, Julian Francis' , size: 3},
{ text: 'Halliday, David M' , size: 3},
{ text: 'Kantharaju, Pavan' , size: 3},
{ text: 'Onta{\~n}{\'o}n, Santiago' , size: 9},
{ text: 'Zhou, Yushan' , size: 3},
{ text: 'Li, Wenxin' , size: 3},
{ text: 'Bistritz, Ilai' , size: 3},
{ text: 'Leshem, Amir' , size: 3},
{ text: 'Volkmar, Georg' , size: 3},
{ text: 'Yannakakis, Georgios N' , size: 9},
{ text: 'Huang, Chao' , size: 3},
{ text: 'Zhang, Like' , size: 3},
{ text: 'Jing, Yanqing' , size: 3},
{ text: 'Zhou, Dajun' , size: 3},
{ text: 'Baier, Hendrik' , size: 9},
{ text: 'Sattaur, Adam' , size: 3},
{ text: 'Powley, Edward J' , size: 3},
{ text: 'Cowling, Peter I' , size: 3},
{ text: 'Soemers, Dennis JNJ' , size: 6},
{ text: 'Schuster, Torsten' , size: 3},
{ text: 'Ariyurek, Sinan' , size: 3},
{ text: 'Betin-Can, Aysu' , size: 3},
{ text: 'Surer, Elif' , size: 3},
{ text: 'Babadi, Amin' , size: 3},
{ text: 'Omoomi, Behnaz' , size: 3},
{ text: 'Kendall, Graham' , size: 3},
{ text: 'Rodgers, Philip' , size: 3},
{ text: 'Guerrero-Romero, Cristina' , size: 9},
{ text: 'Kristensen, Jeppe Theiss' , size: 6},
{ text: 'Valdivia, Arturo' , size: 3},
{ text: 'Burelli, Paolo' , size: 6},
{ text: 'Partlan, Nathan' , size: 6},
{ text: 'Carstensdottir, Elin' , size: 6},
{ text: 'Kleinman, Erica' , size: 3},
{ text: 'Snodgrass, Sam' , size: 3},
{ text: 'Matuk, Camillia' , size: 3},
{ text: 'Sutherland, Steven C' , size: 3},
{ text: 'El-Nasr, Magy Seif' , size: 3},
{ text: 'Dubey, Rahul' , size: 3},
{ text: 'Ghantous, Joseph' , size: 3},
{ text: 'Louis, Sushil' , size: 3},
{ text: 'Liu, Siming' , size: 3},
{ text: 'Smith, Robert J' , size: 3},
{ text: 'Heywood, Malcolm I' , size: 6},
{ text: 'Lockett, Alan J' , size: 3},
{ text: 'Chen, Charles L' , size: 3},
{ text: 'Miikkulainen, Risto' , size: 9},
{ text: 'Frankland, Clive' , size: 3},
{ text: 'Pillay, Nelishia' , size: 3},
{ text: 'Carvelli, Christian' , size: 3},
{ text: 'Grbic, Djordje' , size: 3},
{ text: 'Bulitko, Vadim' , size: 3},
{ text: 'Shaker, Noor' , size: 3},
{ text: 'Shaker, Mohammad' , size: 3},
{ text: 'Wilson, Dennis G' , size: 3},
{ text: 'Cussat-Blanc, Sylvain' , size: 3},
{ text: 'Luga, Herv{\'e}' , size: 3},
{ text: 'Miller, Julian F' , size: 3},
{ text: 'Thompson, Thomas' , size: 3},
{ text: 'Hayes, Gillian' , size: 3},
{ text: 'Silva, Fernando De Mesentier' , size: 3},
{ text: 'Borovikov, Igor' , size: 6},
{ text: 'Kolen, John' , size: 6},
{ text: 'Aghdaie, Navid' , size: 3},
{ text: 'Zaman, Kazi' , size: 3},
{ text: 'Bhatt, Aditya' , size: 3},
{ text: 'Watson, Connor W' , size: 3},
{ text: 'Yan, Song' , size: 3},
{ text: 'Yingfeng, Chen' , size: 3},
{ text: 'Yujing, Hu' , size: 3},
{ text: 'Changjie, Fan' , size: 3},
{ text: 'Thielscher, Michael' , size: 12},
{ text: 'Gonz{\'a}lez-Duque, Miguel' , size: 3},
{ text: 'Palm, Rasmus Berg' , size: 3},
{ text: 'Ha, David' , size: 3},
{ text: 'Kaiser, Lukasz' , size: 6},
{ text: 'Stafiniak, Lukasz' , size: 3},
{ text: 'Parker, Gary' , size: 3},
{ text: 'Fritzsche, Phil' , size: 3},
{ text: 'Schiffel, Stephan' , size: 6},
{ text: 'Synnaeve, Gabriel' , size: 3},
{ text: 'Lin, Zeming' , size: 3},
{ text: 'Gehring, Jonas' , size: 3},
{ text: 'Gant, Dan' , size: 3},
{ text: 'Mella, Vegard' , size: 3},
{ text: 'Khalidov, Vasil' , size: 3},
{ text: 'Carion, Nicolas' , size: 3},
{ text: 'Usunier, Nicolas' , size: 3},
{ text: 'Bravi, Ivan' , size: 9},
{ text: 'Volz, Vanessa' , size: 3},
{ text: 'Lucas, Simon' , size: 12},
{ text: 'Konen, Wolfgang' , size: 3},
{ text: 'Banerjee, Bikramjit' , size: 3},
{ text: 'Stone, Peter' , size: 6},
{ text: 'Finnsson, Hilmar' , size: 6},
{ text: 'Liu, Jialin' , size: 12},
{ text: 'Ashlock, Daniel' , size: 9},
{ text: 'Saunders, Amanda' , size: 3},
{ text: 'Lantz, Frank' , size: 3},
{ text: 'Agapitos, Alexandros' , size: 3},
{ text: 'Schmidhuber, Jurgen' , size: 3},
{ text: 'Konstantinidis, Andreas' , size: 3},
{ text: 'Holmgard, Christoffer' , size: 3},
{ text: 'Canaan, Rodgrigo' , size: 3},
{ text: 'Yang, Zuozhi' , size: 3},
{ text: 'Kaisers, Michael' , size: 3},
{ text: 'Churchill, David' , size: 6},
{ text: 'Mendes, Andre' , size: 6},
{ text: 'Hausknecht, Matthew' , size: 3},
{ text: 'Khandelwal, Piyush' , size: 3},
{ text: 'Schofield, Michael' , size: 6},
{ text: 'Cerexhe, Timothy' , size: 3},
{ text: 'Li, Wanxiang' , size: 3},
{ text: 'Hsueh, Chu-Hsuan' , size: 3},
{ text: 'Ikeda, Kokolo' , size: 3},
{ text: 'Oh, In-Seok' , size: 3},
{ text: 'Cho, Ho-Chul' , size: 3},
{ text: 'Kim, Kyung-Joong' , size: 6},
{ text: 'Tan, Chek Tien' , size: 6},
{ text: 'Cheng, Ho-lun' , size: 6},
{ text: 'Liang, Claire' , size: 3},
{ text: 'Proft, Julia' , size: 3},
{ text: 'Andersen, Erik' , size: 3},
{ text: 'Knepper, Ross A' , size: 3},
{ text: 'Frazier, Spencer' , size: 3},
{ text: 'Riedl, Mark' , size: 6},
{ text: 'Srinivasan, Sriram' , size: 3},
{ text: 'Talvitie, Erik' , size: 3},
{ text: 'Bowling, Michael' , size: 3},
{ text: 'Uriarte, Alberto' , size: 3},
{ text: 'Solinas, Christopher' , size: 3},
{ text: 'Rebstock, Douglas' , size: 3},
{ text: 'Ouessai, Abdessamed' , size: 3},
{ text: 'Salem, Mohammed' , size: 3},
{ text: 'Mora, Antonio M' , size: 3},
{ text: 'Reeder, John' , size: 3},
{ text: 'Gita, Sukthankar' , size: 3},
{ text: 'Georgiopoulos, Michael' , size: 3},
{ text: 'Anagnostopoulos, Georgios' , size: 3},
{ text: 'Barros, Gabriella' , size: 3},
{ text: 'Suetake, Hirotaka' , size: 3},
{ text: 'Fukusato, Tsukasa' , size: 3},
{ text: 'Arzate Cruz, Christian' , size: 3},
{ text: 'Igarashi, Takeo' , size: 3},
{ text: 'Frydenberg, Frederik' , size: 3},
{ text: 'Andersen, Kasper R' , size: 3},
{ text: 'Perez, Diego' , size: 6},
{ text: 'Chang, Yu-Han' , size: 3},
{ text: 'Maheswaran, Rajiv' , size: 3},
{ text: 'Levinboim, Tomer' , size: 3},
{ text: 'Rajan, Vasudev' , size: 3},
{ text: 'Shao, Kun' , size: 3},
{ text: 'Zhao, Dongbin' , size: 3},
{ text: 'Li, Nannan' , size: 3},
{ text: 'Zhu, Yuanheng' , size: 3},
{ text: 'Peng, Peixi' , size: 3},
{ text: 'Xing, Junliang' , size: 3},
{ text: 'Cao, Lili' , size: 3},
{ text: 'Mu, Lisen' , size: 3},
{ text: 'Huang, Chang' , size: 3},
{ text: 'Robotics, Horizon' , size: 3},
{ text: 'Harrison, Brent' , size: 3},
{ text: 'Bj{\""o}rnsson, Yngvi' , size: 3},
{ text: 'McPartland, Michelle' , size: 3},
{ text: 'Gallagher, Marcus' , size: 3},
{ text: 'Adolphs, Leonard' , size: 3},
{ text: 'Hofmann, Thomas' , size: 3},
{ text: 'Canaan, Rodrigo' , size: 3},
{ text: 'Dockhorn, Alexander' , size: 3},
{ text: 'Fontaine, Matthew C' , size: 3},
{ text: 'Soros, Lisa B' , size: 3},
{ text: 'Kim, Dae-Wook' , size: 3},
{ text: 'Park, Sungyun' , size: 3},
{ text: 'Yang, Seong-il' , size: 3},
{ text: 'Park, Hyunsoo' , size: 3},
{ text: 'Etaner-Uyar, A {\c{S}}ima' , size: 3},
{ text: 'Gero, Katy Ilonka' , size: 3},
{ text: 'Ashktorab, Zahra' , size: 3},
{ text: 'Dugan, Casey' , size: 3},
{ text: 'Pan, Qian' , size: 3},
{ text: 'Johnson, James' , size: 3},
{ text: 'Geyer, Werner' , size: 3},
{ text: 'Ruiz, Maria' , size: 3},
{ text: 'Miller, Sarah' , size: 3},
{ text: 'Millen, David R' , size: 3},
{ text: 'Campbell, Murray' , size: 3},
{ text: 'Isaksen, Aaron' , size: 3},
{ text: 'Greenwood, Garrison W' , size: 3},
{ text: 'Ciancarini, Paolo' , size: 3},
{ text: 'Favini, Gian Piero' , size: 3},
{ text: 'Tak, Mandy JW' , size: 3},
{ text: 'Lanctot, Marc' , size: 6},
{ text: 'Pepels, Tom' , size: 3},
{ text: 'Sturtevant, Nathan R' , size: 3},
{ text: 'Jacobsen, Emil Juul' , size: 3},
{ text: 'Greve, Rasmus' , size: 3},
{ text: 'Mostaghim, Sanaz' , size: 6},
{ text: 'Kelly, Stephen' , size: 3},
{ text: 'Cazenave, Tristan' , size: 3},
{ text: 'Saffidine, Abdallah' , size: 3},
{ text: 'Mari{\~n}o, Julian' , size: 3},
{ text: 'Fasli, Maria' , size: 3},
{ text: 'Paquette, Philip' , size: 3},
{ text: 'Lu, Yuchen' , size: 3},
{ text: 'BOCCO, SETON STEVEN' , size: 3},
{ text: 'Smith, Max' , size: 3},
{ text: 'O.-G., Satya' , size: 3},
{ text: 'Kummerfeld, Jonathan K.' , size: 3},
{ text: 'Pineau, Joelle' , size: 3},
{ text: 'Courville, Aaron C' , size: 3},
{ text: 'Gibson, Richard' , size: 3},
{ text: 'Perez Liebana, Diego' , size: 3},
{ text: 'Dieskau, Jens' , size: 3},
{ text: 'Hunermund, Martin' , size: 3},
{ text: 'Sato, Yoshikuni' , size: 3},
{ text: 'Miwa, Makoto' , size: 3},
{ text: 'Takeuchi, Shogo' , size: 3},
{ text: 'Takahashi, Daisuke' , size: 3},
{ text: 'van den Bergh, Mark JH' , size: 3},
{ text: 'Castelein, Sipke T' , size: 3},
{ text: 'van Gent, Dani{\""e}l MH' , size: 3},
{ text: 'Yau, Yi Jack' , size: 3},
{ text: 'Teo, Jason' , size: 3},
{ text: 'Anthony, Patricia' , size: 3},
{ text: 'Camilleri, Elizabeth' , size: 3},
{ text: 'Dingli, Alexiei' , size: 3},
{ text: 'Min, Wookhee' , size: 3},
{ text: 'Mott, Bradford W' , size: 3},
{ text: 'Rowe, Jonathan P' , size: 3},
{ text: 'Liu, Barry' , size: 3},
{ text: 'Lester, James C' , size: 3},
{ text: 'Liu, Tianyu' , size: 3},
{ text: 'Zheng, Zijie' , size: 3},
{ text: 'Li, Hongchang' , size: 3},
{ text: 'Bian, Kaigui' , size: 3},
{ text: 'Song, Lingyang' , size: 3},
{ text: 'Song, Shihong' , size: 3},
{ text: 'Weng, Jiayi' , size: 3},
{ text: 'Yan, Dong' , size: 3},
{ text: 'Zou, Haosheng' , size: 3},
{ text: 'Yusuf Aytar' , size: 3},
{ text: 'T. Pfaff' , size: 3},
{ text: 'D. Budden' , size: 3},
{ text: 'T. Paine' , size: 3},
{ text: 'Ziyu Wang' , size: 3},
{ text: 'N. D. Freitas' , size: 3},
{ text: 'Nguyen, Kien Quang' , size: 3},
{ text: 'Wang, Zhe' , size: 3},
{ text: 'Roohi, Shaghayegh' , size: 6},
{ text: 'Relas, Asko' , size: 3},
{ text: 'Takatalo, Jari' , size: 6},
{ text: 'Heiskanen, Henri' , size: 3},
{ text: 'H{\""a}m{\""a}l{\""a}inen, Perttu' , size: 6},
{ text: 'Sutherland, Steven' , size: 3},
{ text: 'Duke, Tyler' , size: 3},
{ text: 'Ferris, Erika' , size: 3},
{ text: 'Richter, Robin M' , size: 3},
{ text: 'Valladares, Maria' , size: 3},
{ text: 'Seif El-Nasr, Magy' , size: 3},
{ text: 'Huang, Bojun' , size: 3},
{ text: 'Liskowski, Pawe{\l}' , size: 6},
{ text: 'Bouzy, Bruno' , size: 3},
{ text: 'Rimbaud, Alexis' , size: 3},
{ text: 'Ventos, V{\'e}ronique' , size: 3},
{ text: 'Leece, Michael' , size: 3},
{ text: 'Silver, David' , size: 3},
{ text: 'M{\""u}ller, Martin' , size: 3},
{ text: 'Ivanovic, Jayden' , size: 3},
{ text: 'Zambetta, Fabio' , size: 3},
{ text: 'Li, Xiaodong' , size: 3},
{ text: 'Rivera-Villicana, Jessica' , size: 3},
{ text: 'Braylan, Alexander' , size: 3},
{ text: 'Hollenbeck, Mark' , size: 3},
{ text: 'Meyerson, Elliot' , size: 3},
{ text: 'Guckelsberger, Christian' , size: 3},
{ text: 'Kelly, Richard' , size: 3},
{ text: 'Alam, Muhammad Sajid' , size: 3},
{ text: 'Aljammaz, Rehaf' , size: 3},
{ text: 'Oliver, Elizabeth' , size: 3},
{ text: 'Whitehead, Jim' , size: 6},
{ text: 'Szubert, Marcin' , size: 3},
{ text: 'Ja{\'s}kowski, Wojciech' , size: 3},
{ text: 'Krawiec, Krzysztof' , size: 3},
{ text: 'David-Tabibi, Omid' , size: 3},
{ text: 'Van Den Herik, H Jaap' , size: 3},
{ text: 'Koppel, Moshe' , size: 3},
{ text: 'Netanyahu, Nathan S' , size: 3},
{ text: 'Pacheco, Cristiana' , size: 3},
{ text: 'Tokarchuk, Laurissa' , size: 3},
{ text: 'Kumari, Shringi' , size: 3},
{ text: 'Deterding, Sebastian' , size: 3},
{ text: 'Bolander, Thomas' , size: 3},
{ text: 'Pjetursson, Jacob' , size: 3},
{ text: 'Cou{\""e}toux, Adrien' , size: 3},
{ text: 'Vodopivec, Tom' , size: 3},
{ text: 'Kirchge{\ss}ner, Florian' , size: 3},
{ text: 'Shoham, Yaron' , size: 3},
{ text: 'Schaeffer, Jonathan' , size: 3},
{ text: 'White, Christopher D' , size: 3},
{ text: 'Brogan, Dave' , size: 3},
{ text: 'Kim, Eun-Youn' , size: 3},
{ text: 'Perez-Lebana, Diego' , size: 3},
{ text: 'Brown, Joseph Alexander' , size: 3},
{ text: 'Nielsen, Thorbj{\o}rn S' , size: 3},
{ text: 'Nelson, Mark J' , size: 3},
{ text: 'Siljebr{\aa}t, Henrik' , size: 3},
{ text: 'Addyman, Caspar' , size: 3},
{ text: 'Pickering, Alan' , size: 3},
{ text: 'Paliyawan, Pujana' , size: 3},
{ text: 'Sookhanaphibarn, Kingkarn' , size: 3},
{ text: 'Choensawat, Worawat' , size: 3},
{ text: 'Sharma, Manu' , size: 3},
{ text: 'Holmes, Michael P' , size: 3},
{ text: 'Santamar{\'\i}a, Juan Carlos' , size: 3},
{ text: 'Irani, Arya' , size: 3},
{ text: 'Isbell Jr, Charles Lee' , size: 3},
{ text: 'Ram, Ashwin' , size: 3},
{ text: 'R. Balla' , size: 3},
{ text: 'Alan Fern' , size: 3},
{ text: 'Oh, Changhoon' , size: 3},
{ text: 'Lee, Taeyoung' , size: 3},
{ text: 'Kim, Yoojung' , size: 3},
{ text: 'Park, SoHyun' , size: 3},
{ text: 'Kwon, Saebom' , size: 3},
{ text: 'Suh, Bongwon' , size: 3},
{ text: 'Lorenzo, Francesco' , size: 3},
{ text: 'Asadi, Sahar' , size: 3},
{ text: 'Karnsund, Alice' , size: 3},
{ text: 'Cao, Lele' , size: 3},
{ text: 'Wang, Tianze' , size: 3},
{ text: 'Payberah, Amir H' , size: 3},
{ text: 'Leigh, Ryan' , size: 3},
{ text: 'Schonfeld, Justin' , size: 3},
{ text: 'Louis, Sushil J' , size: 3},
{ text: 'Kiourt, Chairi' , size: 3},
{ text: 'Kalles, Dimitris' , size: 3},
{ text: 'Oommen, B John' , size: 3},
{ text: 'Granmo, Ole-Christoffer' , size: 3},
{ text: 'Pedersen, Asle' , size: 3},
{ text: 'Agarwal, Shivam' , size: 3},
{ text: 'Herrmann, Christian' , size: 3},
{ text: 'Wallner, G{\""u}nter' , size: 3},
{ text: 'Beck, Fabian' , size: 3},
{ text: 'Geffner, Tomas' , size: 3},
{ text: 'Zhao, Yunqi' , size: 3},
{ text: 'Beirami, Ahmad' , size: 3},
{ text: 'Rupert, Jason' , size: 3},
{ text: 'Somers, Caedmon' , size: 3},
{ text: 'Harder, Jesse' , size: 3},
{ text: 'Pinto, Jervis' , size: 3},
{ text: 'Pourabolghasem, Reza' , size: 3},
{ text: 'Aytemiz, Batu' , size: 3},
{ text: 'Shu, Xueer' , size: 3},
{ text: 'Hu, Eric' , size: 3},
{ text: 'Smith, Adam' , size: 3}
    ];

// Next you need to use the layout script to calculate the placement, rotation and size of each word:

var width = 1000;
var height = 1000;
var fill = d3.scale.category20();

    d3.layout.cloud()
    	.size([width, height])
    	.words(skillsToDraw)
    	.rotate(function() {
    		return ~~(Math.random() * 2) * 0;
    	})
    	.font("Impact")
    	.fontSize(function(d) {
    		return d.size;
    	})
    	.on("end", drawSkillCloud)
    	.start();

// Finally implement `drawSkillCloud`, which performs the D3 drawing:

    // apply D3.js drawing API
    function drawSkillCloud(words) {
    	d3.select("#cloud").append("svg")
    		.attr("width", width)
    		.attr("height", height)
    		.append("g")
    		.attr("transform", "translate(" + ~~(width / 2) + "," + ~~(height / 2) + ")")
    		.selectAll("text")
    		.data(words)
    		.enter().append("text")
    		.style("font-size", function(d) {
    			return d.size + "px";
    		})
    		.style("-webkit-touch-callout", "none")
    		.style("-webkit-user-select", "none")
    		.style("-khtml-user-select", "none")
    		.style("-moz-user-select", "none")
    		.style("-ms-user-select", "none")
    		.style("user-select", "none")
    		.style("cursor", "default")
    		.style("font-family", "Impact")
    		.style("fill", function(d, i) {
    			return fill(i);
    		})
    		.attr("text-anchor", "middle")
    		.attr("transform", function(d) {
    			return "translate(" + [d.x, d.y] + ")rotate(" + d.rotate + ")";
    		})
    		.text(function(d) {
    			return d.text;
    		});
    }
    
// set the viewbox to content bounding box (zooming in on the content, effectively trimming whitespace)

    var svg = document.getElementsByTagName("svg")[0];
    var bbox = svg.getBBox();
    var viewBox = [bbox.x, bbox.y, bbox.width, bbox.height].join(" ");
    svg.setAttribute("viewBox", viewBox);